version: "3"
services:
  app:
    container_name: React_container
    build: docker/
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
    stdin_open: true
    tty: true
    environment:
      TZ: Asia/Tokyo
